### PR TITLE
Concrete Chemical Formula

### PR DESCRIPTION
**Pull request by rfellers**
- Removes IChemicalFormula in favor of a concrete ChemicalFormula class only. Removing flexibility point allows for increased performance of this low-level class because we don't need to make generic `Equals()` and `GetHashCode()` implementations. Obvious downside is that users won't be able to make their own implementation of IChemicalFormula and pull it in. Please let me know your thoughts!
- Implements a common vs. uncommon element approach in chemical formula to make the common path very fast while keeping memory overhead low. The six elements used in amino acids are stored in dedicated arrays to make all operations faster. If other elements are used, they are stored in an uncommon list. Everything is created as needed to keep memory pressure low.

### CODE REVIEW

**Review by acesnik — COMMENTED** [review]
I don't foresee anyone needing to reimplement the chemical formula class... How similar is this to the internal code on your side? Are you using this class internally?

Here is our chemical formula implementation. https://github.com/smith-chem-wisc/mzLib/blob/master/mzLib/Chemistry/ChemicalFormula.cs

@trishorts @Alexander-Sol @nbollis I wonder if you have any thoughts on this from a future integration perspective.

**Review by acesnik — APPROVED** [review]

**Comment by rfellers** [comment]
thanks @acesnik! In the most recent version of our internal libraries, we took a dependency on TD SDK. No better way to find problems than to dogfood it, right?! This is how we ran into this performance problem. This PR approach is moving in the direction of mzLib (concrete class, no interface), but it is immutable where mzLib's can be changed. I personally think this is a safer way to go, but I'm up for the debate! Thanks again.

**Comment by acesnik** [comment]
I think you're right that it's safer. I'm not sure if we actually have an instance where we're changing the formula; they're usually just instantiated with a different formula.

**Comment by acesnik** [comment]
Feel free to merge this. We can discuss mzLib integration details on a different forum if needed.

**Comment by acesnik** [comment]
It looks like you still have NETStandard2.1 cases in there; can these be removed, since that framework is deprecated?

**Comment by rfellers** [comment]
> It looks like you still have NETStandard2.1 cases in there; can these be removed, since that framework is deprecated?

We added multiple targeting on library awhile back to support .NET 4.7.2, so that's where all the conditional #ifdefs are coming from. Please correct me if I'm wrong, but I don't think .NET Standard is deprecated, but more not being updated. If one isn't using features beyond .NET Standard 2.1, I think it is still the best target to use to support .NET Core 3.1 and newer.

**Pull request merged**
